#Application url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#url=http://localhost/orangehrm/web/index.php/auth/login

#Browser configuration
browser = chrome

#User credentails
usenName = admin
password = admin123

#Browser Implicit wait (in seconds)
implicitWait = 10


#Browser Explicit wait (in seconds)
explicitWait = 30